version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run bootstrap
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  build:
    jobs:
      - build
